[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "opendrive-xai"
version = "0.0.1"
description = "OpenDrive-XAI research stack"
authors = [{name='Pasqui', email=''}]
readme = "README.md"
requires-python = ">=3.9" 